version: '2'
services:
  phpalumno:
    build:
      context: ./
      dockerfile: Dockerfiles/DockerAppAlumno
    tty: true
    restart: unless-stopped
    ports:
      - "8080:80"
  phpdocente:
    build:
      context: ./
      dockerfile: Dockerfiles/DockerAppDocente
    tty: true
    restart: unless-stopped
    ports:
      - "8081:80"
  mysql:
    image: mysql:5.7
    tty: true 
    ports:
      - "3306:3306"
    restart: unless-stopped 
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./AppDB/mysql:/var/lib/mysql
