version: '2'
services:
  phpalumno:
    build:
      context: ./
      dockerfile: Dockerfiles/DockerAppAlumno
    tty: true
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./AppAlumno/:/var/www/html
      - ./AppAlumno/EsilumBackEnd/:/var/www/html/EsilumBackEnd/
      
  phpdocente:
    build:
      context: ./
      dockerfile: Dockerfiles/DockerAppDocente
    tty: true
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./AppDocente/:/var/www/html
      - ./AppDocente/EsilumBackEnd/:/var/www/html/EsilumBackEnd/

  phpadmin:
    build:
      context: ./
      dockerfile: Dockerfiles/DockerAppAdmin
    tty: true
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./AppAdmin/:/var/www/html
      - ./AppAdmin/EsilumBackEnd/:/var/www/html/EsilumBackEnd/
      
  mysql:
    image: mysql:5.7
    tty: true 
    ports:
      - "3306:3306"
    restart: unless-stopped 
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=base
    volumes:
      - ./AppDB/mysql:/var/lib/mysql
