- name: Abrir puertos de mysql y ssh en firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  loop:
    - 3306/tcp
    - 2244/tcp
    
- name: recargarfirewall
      systemd:
        name: firewalld
        state: reloaded